# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_user_detailed_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_user',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
